//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuGet.Forms.Localisation {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MuGet.Forms.Localisation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string ItemDashItem {
            get {
                return ResourceManager.GetString("ItemDashItem", resourceCulture);
            }
        }
        
        public static string ItemToItem {
            get {
                return ResourceManager.GetString("ItemToItem", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string ItemSpaceItem {
            get {
                return ResourceManager.GetString("ItemSpaceItem", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string StringJoinComma {
            get {
                return ResourceManager.GetString("StringJoinComma", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string ItemLatestVersion {
            get {
                return ResourceManager.GetString("ItemLatestVersion", resourceCulture);
            }
        }
        
        public static string TotalDownloadsFormat {
            get {
                return ResourceManager.GetString("TotalDownloadsFormat", resourceCulture);
            }
        }
        
        public static string DownloadsOfCurrentVersionFormat {
            get {
                return ResourceManager.GetString("DownloadsOfCurrentVersionFormat", resourceCulture);
            }
        }
        
        public static string DownloadsPerDayFormat {
            get {
                return ResourceManager.GetString("DownloadsPerDayFormat", resourceCulture);
            }
        }
        
        public static string NoDependencies {
            get {
                return ResourceManager.GetString("NoDependencies", resourceCulture);
            }
        }
        
        public static string Depedencies {
            get {
                return ResourceManager.GetString("Depedencies", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        public static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        public static string RunAllJobs {
            get {
                return ResourceManager.GetString("RunAllJobs", resourceCulture);
            }
        }
        
        public static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        public static string IncludePrerelease {
            get {
                return ResourceManager.GetString("IncludePrerelease", resourceCulture);
            }
        }
        
        public static string NoFavouritePackages {
            get {
                return ResourceManager.GetString("NoFavouritePackages", resourceCulture);
            }
        }
        
        public static string NoRecentPackages {
            get {
                return ResourceManager.GetString("NoRecentPackages", resourceCulture);
            }
        }
        
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        public static string NotificationsDescription {
            get {
                return ResourceManager.GetString("NotificationsDescription", resourceCulture);
            }
        }
        
        public static string WelcomeToMuGet {
            get {
                return ResourceManager.GetString("WelcomeToMuGet", resourceCulture);
            }
        }
        
        public static string CannotFindPackage {
            get {
                return ResourceManager.GetString("CannotFindPackage", resourceCulture);
            }
        }
        
        public static string CannotFindPackageDescription {
            get {
                return ResourceManager.GetString("CannotFindPackageDescription", resourceCulture);
            }
        }
    }
}
